### ISSUE TITLE
String encoding by platformID

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/font-v#1]
Current approach:

```python
if record.platformID == 0:
    record.string = version_string.encode('utf_16_be')  # Unicode platform ID gets UTF16 big endian
elif record.platformID == 1:
    record.string = version_string                      # Mac platform ID
elif record.platformID == 3:
    record.string = version_string.encode('utf_16_be')  # Windows platform ID gets UTF16 big endian
```
TODO: 

- [x] add `from __future__ import unicode_literals` to module
- [x] let fontools encode proper string by platformID type (see https://github.com/source-foundry/font-v/issues/1#issuecomment-327184941)
- [x] use `unicode` alias and `tounicode` function in fonttools py23 module to encode properly before use of fonttools library for the string write (see https://github.com/source-foundry/font-v/issues/1#issuecomment-327191939)
- [x] test encoding of strings and exception handling for string encoding in Py 2 + 3

Per conversations with @davelab6 and @anthrotype, the platformID 1 version strings are **not** used to any significant degree any longer so the platformID writes should see limited use out there.  It sounds as though there is some legacy use of the platformID 1 records on old versions of Mac (maybe even pre OS X) applications.  

Review of numerous fonts (including commercial) shows that the platformID 1 version strings are almost universally present so we should still support the correct modification of this record here.

**Comment by anthrotype** [comment]
You can just set the `record.string` to a unicode string (i.e. `unicode` type in Python 2, or `str` type in Python 3), and let fonttools encode it automatically for you with the correct platform encoding for that name record.

I also recommend to use `from __future__ import unicode_literals` whenever you can, so your string literals are implicitly treated as unicode strings (without needing `u""` in front of them) like in Python 3.

The `fontTools.misc.py23` module has some convenience utilities and type aliases to correctly work with unicode/str/bytes in a py2/py3 environment.

Remember that the list of command line arguments that you get from the console (`sys.argv`) are `bytes` strings on Python 2, and these are encoded with the console's encoding (`UTF-8` on most Unix based systems). On Python 3 on the other hand, they are already decoded to unicode strings (`str`). In the case of python 2, you'll need to know what the console's encoding is (`sys.stdout.encoding` gives you a hint, but the latter may be `None` if standard streams have been redirected to a pipe; you can google for "python 2 sys.argv encoding" or if you feel lazy use "utf-8" all the time!), and then use the console's encoding to decode the arguments to get the unicode strings.

There's a `tounicode` function in `fontTools.misc.py23` that decodes a bytes string to unicode with a given encoding or returns the string as is if it is already a unicode string; useful in these kinds of situations where the input may be either bytes or unicodes and you want unicodes. (also check out `tobytes` and `tostr` functions in same module).

**Comment by chrissimpkins** [comment]
Thank you!  Very helpful!

**Comment by chrissimpkins** [comment]
> You can just set the record.string to a unicode string (i.e. unicode type in Python 2, or str type in Python 3), and let fonttools encode it automatically for you with the correct platform encoding for that name record.

Does the use of the unicode type (even with Python interpreter checking for execution of the code) raise exceptions on Python 3?  i.e. do I catch this exception and ignore when Python 3 interpreter in use?

**Comment by chrissimpkins** [comment]
> There's a tounicode function in fontTools.misc.py23 that decodes a bytes string to unicode with a given encoding or returns the string as is if it is already a unicode string; useful in these kinds of situations where the input may be either bytes or unicodes and you want unicodes. (also check out tobytes and tostr functions in same module).

Will check out these functions.  Very helpful.  Thank you!

**Comment by anthrotype** [comment]
The `unicode` type in Python 2 is the equivalent of the `str` type in Python 3. Hence the `py23` module in fonttools export a `unicode` alias that points to `unicode` in Python 2 and to `str` in Python 3. You can import that `unicode` type from `py23` module and use it, e.g., with `isinstance`.

If you want to convert a `bytes` string to a `unicode` string (in Python 2, which is the same as a `str` string in Python 3), you can use the `tounicode` function from the fonttools `py23` module, which will just pass it on as is if it's already a unicode string, or decode the bytes string to a unicode string using the provided encoding (it defaults to `ascii` but you should provide the actual bytes string encoding; if you read the bytes from a text file, that would usually be UTF-8, if you read them from the console (in Python 2) it will be the console's encoding, etc.).

If you want to work with strings in a codebase that's meant to support both python 2 and 3, I'm afraid you need to become familiar with terms like bytes, unicode, str, encode, decode, etc.
In an ideal world where everybody is using python 3, then one would just use `str` for text, and `bytes` for binary data, without confusing one with the other like python 2 used to do. ;)

**Comment by anthrotype** [comment]
Also note that the stuff in fonttools py23 module is nothing fancy, Other popular python packages that are not afraid of adding dependencies just use the `six` module (https://pythonhosted.org/six/) which provides the same (and more) functionalities. But since your library already depends on fonttools, you may well just use that.

**Comment by chrissimpkins** [comment]
> But since your library already depends on fonttools, you may well just use that.

👍   Thanks Cosimo.  This is very helpful.  I will tinker in Py2/3 once I get the Travis testing set up for the project.

**Comment by chrissimpkins** [comment]
Added the following to the TODO list based upon above conversation:

- add `from __future__ import unicode_literals` to module
- let fontools library encode proper string by platformID type, ignore this on font-v end (see https://github.com/source-foundry/font-v/issues/1#issuecomment-327184941)
- use `unicode` alias and `tounicode` function in fonttools py23 module to encode properly before use of fonttools library for the string write - i.e. before `record.string` definitions (see https://github.com/source-foundry/font-v/issues/1#issuecomment-327191939)
- test encoding of strings and exception handling for string encoding in Py 2 + 3 on Travis

**Comment by chrissimpkins** [comment]
👍 tests...

```python
from fontTools.misc.py23 import unicode, tounicode, tobytes, tostr


def test_fontv_fonttools_lib_unicode():
    test_string = tobytes("hello")
    test_string_str = tostr("hello")
    test_string_unicode = tounicode(test_string, 'utf-8')

    assert (isinstance(test_string, unicode)) is False
    if sys.version_info[0] == 2:
        assert (isinstance(test_string_str, unicode)) is False    # str != unicode in Python 2
    elif sys.version_info[0] == 3:
        assert (isinstance(test_string_unicode, unicode)) is True  # str = unicode in Python 3
    assert test_string_unicode == "hello"
```

**Comment by chrissimpkins** [comment]
My head is spinning after a lengthy attempt to perform a string equality comparison between the name record `record.string` that is read in from fonttools and a string literal across combinations of the unicode_literals import/attempts to cast to unicode with fonttools `tounicode` function, use of str.decode('utf-8'), etc.  I need to do this in order to confirm that I am not saving a previous sha1 string/dev string/release string after I split the complete version string on semicolons to a list.

What I am looking to do is something along these lines:

```
version_list = record.string.split(";")
keep_list = []
for substring in version_list[1:]: # exclude the Version X.X string that is held in another variable
    if substring.strip() == "DEV" or substring.strip() == "RELEASE":
        pass
    else:
        keep_list.append(substring)

post_version_string = ";".join(keep_list)

# full version string is concatenated from variables above this level , new content based upon user command line request, and the above post_version_string appended to maintain anything that user previously had following a semicolon
```

Thoughts?  Despite being able to cast everything to same type in Python 2 <str> v <str> and <unicode> v <unicode>, the string equality comparison always yields False.  This is what I am seeing for the version_list with data read from fonttools following the split on semicolons for a font with a version string that reads `Version 1.000; DEV`:

```
['\x00\x00\x00V\x00\x00\x00e\x00\x00\x00r\x00\x00\x00s\x00\x00\x00i\x00\x00\x00o\x00\x00\x00n\x00\x00\x00 \x00\x00\x001\x00\x00\x00.\x00\x00\x000\x00\x00\x000\x00\x00\x000\x00', '\x00 \x00D\x00E\x00V']
```

**Comment by anthrotype** [comment]
When fonttools decompiles a font, the record.string you get is of type bytes; if you want to decode it to a Unicode string you need to call the NameRecord's `toUnicode()` method. That's used e.g. when fonttools dumps the name record to TTX.
Check the inline documentation in the name table module.

**Comment by anthrotype** [comment]
https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/_n_a_m_e.py#L326

**Comment by chrissimpkins** [comment]
I think that this was the problem.  They must be utf16 big endian encoded data (or some other non-utf8 encoding).  I was trying to cast to unicode with the py23.misc.tounicode function and specifying utf8.  Will check it today with the table specific unicode casting function.  Thanks Cosimo.

**Comment by chrissimpkins** [comment]
It looks like the name table specific `toUnicode` function uses `tounicode` internally so I am working under the assumption that we are still going to be dealing with str types on Py3 and unicode types on Py 2.  We will see...

**Comment by anthrotype** [comment]
yes, `toUnicode()` method of NameRecord returns a `unicode` string in Python 2 (which is the same as a `str` string in Python 3). It automatically decodes it using the right encoding.

**Comment by chrissimpkins** [comment]
Perfect!  Thank you Cosimo!

A very valuable (and painful) lesson in Py2/3 string handling :)

**Comment by chrissimpkins** [comment]
Are the OpenType tables stored in binaries as C structs with a defined byte length of padding?  This appears to be how they are being unpacked in fonttools.

**Comment by anthrotype** [comment]
You ask out of curiosity? That's an implementation detail.
You can trust FontTools is Doing The Right Thing (TM).

**Comment by anthrotype** [comment]
I'm joking of course. Have a look at the compile method of the name table class if you are interested in understanding how that's done.

**Comment by chrissimpkins** [comment]
Oh yes, simply for my own knowledge.  I fully trust fonttools.  Was going to dust off my C and tinker a bit to better understand the binary.

**Comment by chrissimpkins** [comment]
Your suggestions addressed the issue.  Fixed!

![screenshot at sep 06 09-50-47](https://user-images.githubusercontent.com/4249591/30115493-ee64fcb4-92e8-11e7-9ef4-dbec8a410b76.png)

**Comment by anthrotype** [comment]
Nice! if you're terminal supports UTF-8, you should be even able to put an emoji in your version string 😄  (well, not in the Mac Roman one of course but that's legacy)

**Comment by anthrotype** [comment]
sorry, actually I just realised that the tool is not meant to take arbitrary strings from the console, but just numeric strings like "2_000", so all my ramblings on the encoding of the sys.argv is misplaced since you're guaranteed to receive only ascii characters like digits and underscores.
You can decode the arguments with `tounicode(s, encoding="ascii")` and if it fails with UnicodeDecodeError, it's the user's fault ;)

**Comment by chrissimpkins** [comment]
haha!  for a future release perhaps?

**Comment by chrissimpkins** [comment]
> tounicode(s, encoding="ascii") and if it fails with UnicodeDecodeError, it's the user's fault ;)

I like it when it is not my fault...

**Comment by chrissimpkins** [comment]
Is the default 'ascii' encoding on tounicode stable?  necessary to specify it explicitly?

**Comment by anthrotype** [comment]
it's the default, it won't change. you can just call `tounicode(s)`

**Comment by anthrotype** [comment]
but explicit is better than implicit ;)

**Comment by chrissimpkins** [comment]
> sorry, actually I just realised that the tool is not meant to take arbitrary strings from the console

Currently supports the following:
- modification of the version integers based upon console entry
- addition of a DEV or RELEASE tag in the string as additional (post semicolon) meta data
- addition of the repository git commit short sha1 string with optional `-dev` or `-release` tag added to the sha1

**Comment by chrissimpkins** [comment]
So you can make the following:

- `Version 1.001`
- `Version 1.001; DEV` or `Version 1.001; RELEASE`
- `Version 1.001; 8ca53c6`
- `Version 1.001; 8ca53c6 -dev` or `Version 1.001; 8ca53c6-release`

**Comment by anthrotype** [comment]
cool. all ascii-safe

**Comment by chrissimpkins** [comment]
We are going to use it to add the build git commit SHA1 to Hack

**Comment by chrissimpkins** [comment]
Thanks again for all of your help Cosimo.  I really appreciate all of your time.  This was helpful.

**Comment by chrissimpkins** [comment]
@anthrotype 

Cosimo, is any of this code of interest in fontmake?  If you have any interest in supporting this version (dev/release/sha1) approach, it probably makes more sense to have in a compiler rather than yet one more post compilation adjustment tool.   The tool here could be used for one off changes and for those who do not use fontmake.

**Comment by anthrotype** [comment]
I'm not particularly interested myself, but you are welcome to open an issue on fontmake's repo and see whether others would be interested, or you can propose a pull request.

**Comment by chrissimpkins** [comment]
@anthrotype no worries.  if there isn't buy-in from maintainer won't be worth the time at this stage.  will forge ahead here and see if the approach is attractive to anyone else out there.  if so will pitch it on fontmake repo down the road :)

thanks!

**Comment by chrissimpkins** [comment]
@anthrotype Cosimo, I am getting the following error when I concatenate strings pulled in from fontTools nameID 5 with the git sha1 strings and string literals (e.g. '-dev', '-release') here.  

https://github.com/source-foundry/font-v/issues/12

It seems that the parts (i.e. the concatenated portions between semicolons) are not encoded in the same way and it leads to an odd spacing between characters display in the image in that IR, and more importantly, does not lead to a display of the version string in FontBook on OS X.

The current approach is to pull the "pre" version string as built from source via the fontTools namerecord.toUnicode() method:

```python
            namerecord_list = tt['name'].names
            for record in namerecord_list:
                if record.nameID == 5:

               # ... full nameID record string is cast with .toUnicode method from fontTools library
```

then I split the string on semicolons into a Python list.  The list parts are concatenated to a new nameID 5 version string with a combination of string literals and the git SHA1 short code that is returned by the gitpython library.  It seems that the second list item that includes the sha1 string +/- any string literals is properly formatted but the `Version X.XXX` string (direct from fontTools library and maintained in the list) and the `ttfautohint...` string (direct from fontTools library and maintained in the list prior to concatenation) do not appear to have proper formatting following the write out to the font binary.

Do I need to encode the entire concatenated string in some way before I send it to fontTools for the write?  I am assuming that I am dealing with different string formats for some reason here, but thought that Python (during concatenation) or fontTools would automate these casts in a way that it does not need to be explicit on my end.  Thoughts?

**Comment by anthrotype** [comment]
> the git SHA1 short code that is returned by the gitpython library

you sure that is a `unicode` string and not a `bytes` string? Use `tounicode()` function to ensure it is a `unicode` string (import it from `fonttools.misc.py23` module).

Concatenating unicode and bytes in Python 2 would automatically decode the latter (upgrade them to unicode) using the default ascii encoding. In Python 3, attempting to do `u"abc" + b"abc"` raises TypeError (rightly so). So, in a py2.py3 world, it's better you make sure you are dealing with either or the other, and not mix them up.

The NameRecord `string` attribute can take either a unicode string or a bytes string. In the first case, it will encode it automatically for you next time you compile; in the latter case, it will assume you already encoded the bytes string with the right encoding and will just write it as is. If the bytes were not encoded with the right encoding, you may get garbage like the one in the screenshot.

**Comment by chrissimpkins** [comment]
Hmmm... that may be the case.  Interestingly that is the portion of the string (the git sha1) that does not seem to be affected in the font's version string after write.  Will attempt to cast the string returned by gitpython to unicode with `tounicode` from the py23 module.  It should not be necessary to cast the string literals explicitly before concatenation correct?  My understanding is that the addition of the line 

```python
from __future__ import unicode_literals
``

should force string literals in Py2 to `unicode` and Py3 as `str`, correct?  If so, this should be consistent with where we are with the other substrings from the original font when we import from the record.string with the .toUnicode() method?

**Comment by anthrotype** [comment]
correct, if you use `unicode_literals`.

**Comment by chrissimpkins** [comment]
Thank you!  Will give it a shot this evening.  Hopefully the fix is this simple... :)

**Comment by chrissimpkins** [comment]
Seems to have fixed it!  

![otm light users ces desktop fonts tests hack-regular ttf otf name list 2017-10-02 23-27-50](https://user-images.githubusercontent.com/4249591/31108783-5a744474-a7c9-11e7-80ac-a59501d550e3.png)

Thanks again for your help Cosimo!  Greatly appreciated!!
