### ISSUE TITLE
print resulting version string upon successfully running the write subcommand

### ISSUE THREAD

**Issue by felipesanches** [source-foundry/font-v#13]
A user will typically want to make sure the new version string is correct / looks good. So it is very likely that the user will run the `report` subcommand right after running the `write` subcommand like this:

![screenshot at 2017-11-20 22 08 37](https://user-images.githubusercontent.com/213676/33047913-6187d0cc-ce3f-11e7-888b-07722744ccc9.png)

Because of that I'd suggest the success message for the `write` subcommand to print something like this instead:

**Version string successfully updated to: "Version 1.006; RELEASE"**

So that there's no need to use `report` right after `write`.

**Comment by chrissimpkins** [comment]
I like it! Thoughts about adding the filepath of the fonts that were modified to that line since you can use wildcards to update multiple fonts at once?

**Comment by chrissimpkins** [comment]
Thoughts about this stdout format?

```
 $ font-v write --rel Hack-Regular.ttf DIN-Regular.ttf

[✓] Hack-Regular.ttf version string was successfully changed to:
Version 1.000; RELEASE; ttfautohint (v1.7) -l 6 -r 50 -G 200 -x 10 -H 181 -D latn -f latn -m "Hack-Regular-TA.txt" -R "Hack-Regular.ttf" -Z 0 -w G -W -t -X ""

[✓] DIN-Regular.ttf version string was successfully changed to:
001.000; RELEASE
```

**Comment by chrissimpkins** [comment]
added support for this in v0.3.3.  Pushed to PyPI.

**Comment by felipesanches** [comment]
Great ! :-D
