### ISSUE TITLE
expose the font version string generation code for third-party programs to use them

### ISSUE THREAD

**Issue by felipesanches** [source-foundry/font-v#14]
Due to https://github.com/googlefonts/fontbakery/issues/1563 I've been wondering. I can do any of these:

* copy/paste some of your python code into FontBakery
* install font-v as a dependency and invoke it using subprocess.popen
* refactor font-v so that the code that generates version strings can be nicely imported into fontbakery and used

I'd definitely prefer the third option!

So, I see that the bulk of the code is on `app.py` inside the main function. Would it be OK to move some of that functionality into a separate python file (it maybe could even be the utils.py file) and then export that as a python module ?

Fontbakery (and any other tool) could then do things like:
```python
from fontv.utils import FontVersionObj as fvo
expected = fvo.compute_version_string(fontpath, sha1=True)
```

**Comment by chrissimpkins** [comment]
Absolutely Felipe.  I have no reservations about this at all and we can do whatever works best for you.  Beyond those suggestions, we could even consider pulling the relevant code out into a separate font version string library project, pushing to PyPI, and have both of our projects use this as a dependency.  It would eliminate the need to import my commandlines library and unnecessary command line parsing code, I/O code in your project.  If those are not significant issues on your end, happy to refactor to a separate module with the source that you need or feel free to submit a PR if you would prefer to do it.

If you would like for me to refactor this, let me know specific parts of the source that are helpful to you.  I can get this done this week.

**Comment by felipesanches** [comment]
Cool! I was reading the code yesterday and I had 2 kinds of thoughts in my head:

* (1) The code seems a bit over complicated for something that should be really a font version format generation method.
* (2) I feel like version string format and command-line interface are mixed into a single bunch of code. It would be really nice to split these things appart. For the sake of legibility but also to improve reusability.

**Comment by felipesanches** [comment]
Oh! And it seems that there are multiple possible font version string "schemas". I wonder what specific combination of metadata should be used by default on a version string (and maybe enforced by projects like Google Fonts as mandatory version markup style)

I got a bit overwhelmed by the length of the string in this example:

```bash
[✓] Hack-Regular.ttf version string was successfully changed to:
Version 1.000; RELEASE; ttfautohint (v1.7) -l 6 -r 50 -G 200 -x 10 -H 181 -D latn -f latn -m "Hack-Regular-TA.txt" -R "Hack-Regular.ttf" -Z 0 -w G -W -t -X ""
```
But I guess that's mostly the collection of ttfautohint attributes, right ?

**Comment by felipesanches** [comment]
in terms of a desired general purpose feature for this code modularization, I would suggest a method that (given a font path, or ttFont) returns a dictionary with the values of each of the info parsed from the version strings in the font. Does it make sense ?

**Comment by chrissimpkins** [comment]
>  (1) The code seems a bit over complicated for something that should be really a font version format generation method.
    (2) I feel like version string format and command-line interface are mixed into a single bunch of code. It would be really nice to split these things appart. For the sake of legibility but also to improve reusability.

It was always intended as a font version modification executable and not a library for external use but we can certainly make it multi-purpose. 

> I wonder what specific combination of metadata should be used by default on a version string

My own recommendation would be the following format:

```
Version x.xxx; sha1-[dev | release]
```

You are correct that the extra data is added by ttfautohint.  We preserve it in Hack to have a history of our hinting approach but it would be nice if this was included elsewhere in the OpenType libraries.  The version string is not the ideal location...

**Comment by chrissimpkins** [comment]
> I would suggest a method that (given a font path, or ttFont) returns a dictionary with the values of each of the info parsed from the version strings in the font. Does it make sense ?

You want to be able to access both pre-modification and new generated (e.g. sha1 short hash strings) in the dictionary or only the current pre-modification version string parts?

The approach here is to read in the current version string, determine what the user wants to modify (could be version number, could be dev/rel indicator, could be git sha1 string, or any combination of these), then concatenate these pre-existing and new parts into a new version string for write.  My read of your request is that you would like to be able to have a function/method return key:value pairs of each of these version sub-strings for a given set of parameters passed to the function/method?

**Comment by chrissimpkins** [comment]
Given that there is a natural order to the strings and that the `Version x.xxx` substring must come first, it may be more straightforward to return a list with the parts in appropriate order?  Unless you intend to eliminate some of the parts (i.e. only write out some parts of a developer's version string and not write others)?  If the latter is the intent we can certainly come up with a naming scheme for dictionary key labels.

**Comment by felipesanches** [comment]
I'm not sure. But I'd work with a dict so tha the API is more useful in general.

**Comment by felipesanches** [comment]
2 methods would make a lot of sens, I think: One for reading the current data in the given font. And another for computing the new data based on attributes passed to the method and based on the local git repo working copy commit.

**Comment by felipesanches** [comment]
Beware that I'm brainstorming here. I won't necessarily use all of this on FontBakery, but I'm trying to think of things that would be useful in a python module for reading version info and computing new values, possibly updating the info in the files.

**Comment by chrissimpkins** [comment]
Brainstorming is good.  Let me give it some thought this week.  Given the needs that you have and the needs here, it might make sense to make a FontVersion object to maintain the substring component data and provide methods for the reads/writes.

Something along the lines of the following:

```python
from fontv.versioner import FontVersion

fv = FontVersion(path="x/x/x", version="1.000", development=True, release=False, gitsha1=True)
fv.read_version()
version_substring = fv.version
devrelease_substring = fv.devrelease
gitsha1_substring = fv.gitsha1

// concatenate these parts however you would like...
```

**Comment by chrissimpkins** [comment]
Having given it a bit more thought, it probably makes more sense to expose changes through public methods rather than through the object instantiation.  I like this form better:

```python
from fontv.versioner import FontVersion

fv = FontVersion(path="x/x/x")
pre_version_substring = fv.version
pre_metadata_substring = fv.metadata

fv.set_version("1.001")  # automated with format Version 1.001
fv.set_gitsha1()  # automated lookup
fv.set_development(gitsha1=True)  # mututally exclusive with below
fv.set_release(gitsha1 = True)  # mututally exclusive with above

version_parts = [fv.version, fv.devrel, pre_metadata_substring]

# or do it yourself with:
# version_string = fv.version + "; " + fv.devrel + "; " + pre_metadata_substring

fv.write_version(fv.get_version_string(version_parts))

# or if concatenate yourself
# fv.write_version(version_string)
```

**Comment by chrissimpkins** [comment]
@felipesanches 
cc: @davelab6 @graphicore

Work is underway on a library for your request.  It will be housed in the `fontv.libfv` module and will include a new `FontVersion` object for read/substring parsing/writes of font version strings.

I am supporting dev/rel substring testing on this end so that implementation of dev/rel (and associated git commit SHA1 strings if used in combination with the dev/rel indicators) checks on your end will be through `FontVersion` object boolean properties and as simple as:

```python
from fontv.libfv import FontVersion

fv = FontVersion("path/to/font")

if fv.contains_status:
    if fv.is_development:
        # handle development labeled font
    elif fv.is_release:
        # handle release labeled font
else:
    # raise warning about lack of DEV/REL status label in the font version string
```

There are currently optional parameters that support modification of the `DEV`, `RELEASE`, `[sha1]-dev`, `[sha1]-release` formatted string labels during instantiation of the `FontVersion` object if you intend to modify fonts via the library and want to use a different format, including order and substring combinations.  Each of the individual version substring data elements that exist at the time of the font read will be available in a combination of Python dictionaries, lists, and strings to combine, revise, and write out however you'd like. 

My plan is to support modification of the version string and font file writes for these updates through public methods on the `FontVersion` object.  This isn't implemented yet but will look something like this:

```python
fv.add_git_commit_sha1(status="development")
# fv.add_git_commit_sha1(status="release")  # alternate for release versions
fv.write_version_string()  # the font binary is now updated with the version string modification
```

You will also have access to the `fontTools.ttFont` object as a `FontVersion` object property to use for your own implementation of writes to the font files if that is a better approach for you.

Hopefully that sounds broad and flexible enough to address anything that you need to address in the version strings on your end.  I will push a pull request once I make a bit more progress this weekend so that you can see source details and weigh in with any recommendations from your perspective.

**Comment by chrissimpkins** [comment]
Available in `libfv` branch of the repository.  Here are a minimal set of docs for you to kick the tires:

```python
from fontv.libfv import FontVersion

# starting version string = "Version 1.000;metadata"
fv = FontVersion("path/to/font")

# ACCESS VERSION STRING DATA
version_substring = fv.version
# or
version_substring = fv.version_string_parts[0]

# CHECK STATUS INDICATOR (i.e. DEV/RELEASE/sha1-dev/sha1-release)
if fv.contains_status():
    if fv.is_development:
        # contains a development status label
    elif fv.is_release:
        # contains a release status label
else:
    # no status indicator

# ACCESS VERSION STATUS SUBSTRING DATA
status_substring = fv.status
# or if known to be set
status_substring = fv.version_string_parts[1]

# ADD DEV/RELEASE SUBSTRING DATA
fv.set_development_status()
print(fv.get_version_string())
# prints "Version 1.000;DEV;metadata"
fv.set_release_status()
print(fv.get_version_string())
# prints "Version 1.000;RELEASE;metadata"

# REPLACE STATUS LABEL WITH GIT COMMIT SHA1 HASH STATUS SUBSTRING
fv.set_git_commit_sha1()
print(fv.get_version_string())
# prints "Version 1.000;[sha1];metadata"
fv.set_git_commit_sha1(development=True)
print(fv.get_version_string())
# prints "Version 1.000;[sha1]-dev;metadata"
fv.set_git_commit_sha1(release=True)
print(fv.get_version_string())
# prints "Version 1.000;[sha1]-release;metadata

# CLEAR ALL METADATA FROM VERSION STRING
fv.clear()
print(fv.get_version_string())
# prints "Version 1.000"

# SET THE VERSION NUMBER
fv.set_version_number("2.000")
print(fv.get_version_string())
# prints "Version 2.000"

# MANUALLY SET THE ENTIRE VERSION STRING
fv.set_version_string("Version 3.000;metadata")
print(fv.get_version_string())
# prints "Version 3.000;metadata"

# WRITE TO FONT BINARY -  on filepath used for FontVersion instantiation by default
fv.write_version_string()
# path/to/font now has version string "Version 3.000;metadata"

# WRITE TO FONT BINARY - new filepath
fv.write_version_string(fontpath="test/NewFont-Regular.ttf")
# test/NewFont-Regular.ttf now has version string "Version 3.000;metadata"
```

**Comment by chrissimpkins** [comment]
Will plan to merge as v0.4.0 once I finish adding tests for all new source and receive your feedback to confirm that this works for you.

**Comment by chrissimpkins** [comment]
@felipesanches @graphicore @davelab6 btw, if you intend to use this library via PyPI install or direct pip install from the Github repository rather than pulling the modules, or subsets of the code, to place within the Font Bakery repository and you want write access on this repo let me know.  Happy to add these permissions so that we can all modify the modules directly.

**Comment by felipesanches** [comment]
hey, @chrissimpkins !

Thanks for all of this. I'll be looking into it today and I'll give you feedback later. Cheers!
