### ISSUE TITLE
Move to Python 3.7+ support (remove Python 3.6 support)

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/font-v#154]
The [gitpython project recently removed Py 3.6 support](https://github.com/gitpython-developers/GitPython/commit/bef218246c9935f0c31b23a17d1a02ac3810301d#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7).  In order to include further library updates we will need to do the same.

Failing CI due to lack of Py 3.6 support in gitpython update ==> https://github.com/source-foundry/font-v/pull/153

**Comment by chrissimpkins** [comment]
@graphicore @felipesanches It looks like this move would affect fontbakery.  I'll hold off for now so that I don't break things in the fontbakery installation, but FWIW it looks like fontTools may be heading in this direction ==> https://github.com/fonttools/fonttools/issues/2350

cc @davelab6

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/fontbakery/issues/3459

**Comment by felipesanches** [comment]
yeah, let's do it!

**Comment by chrissimpkins** [comment]
> yeah, let's do it!

This was merged to fontbakery main.

Anyone have objections to this move?  Please voice them now.  We'll make this change soon.

**Comment by chrissimpkins** [comment]
Closed by #161
