### ISSUE TITLE
`get_git_root_path` only checks three levels up

### ISSUE THREAD

**Issue by dscorbett** [source-foundry/font-v#168]
I’m generating fonts/otf/unhinted/instance_otf/NotoSansDuployan-Regular.otf in a Git repository and trying to use `set_state_git_commit_sha1`, but it can’t determine the commit hash because it can’t find the .git directory. Why is `get_git_root_path` limited to looking three levels up?

**Comment by chrissimpkins** [comment]
I don't recall the decision but I am sure that it was arbitrary and only to establish a sanity check on the dir traversal distance.  I would be happy to take a PR to expand the range so that it meets your requirements.

**Comment by chrissimpkins** [comment]
related #169

**Comment by chrissimpkins** [comment]
We may be able to use a better (i.e. not custom home baked dir traversal) approach.  

I am reading this https://stackoverflow.com/a/957978 at the moment.  

We should consider @madig's finding in #169 as we address this.

**Comment by chrissimpkins** [comment]
> We may be able to use a better (i.e. not custom home baked dir traversal) approach.
> 
> I am reading this https://stackoverflow.com/a/957978 at the moment.
> 
> We should consider @madig's finding in #169 as we address this.

Don't let this scare you away from a PR though if it is more work than you planned.  We can begin by simply extending the traversal range.
