### ISSUE TITLE
Change interpreter to python3

### ISSUE THREAD

**Issue by vvug** [source-foundry/font-v#67]
Hello @chrissimpkins, it seems that your code supports Python 3, but by default the interpreter which is used is `python`, that is Python 2. This won't work out-of-the-box on Python3-only installations. Also, Python2 is going to reach its end of life in about one year. Please switch to `python3`.

**Comment by chrissimpkins** [comment]
Thanks for the reminder! Will do!

**Comment by chrissimpkins** [comment]
Coming soon.  

The fontTools library is transitioning to Py3.6+ support as of the v4.0.0 library release.  This project will be updated with changes that eliminate support for Py2.7 and bump the Py3 interpreter version to Py3.6+.

Sorry for the delay here @vvug
