### ISSUE TITLE
Remove previous release / dev tag when present

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/font-v#7]
e.g. 

`Version 1.000; DEV` should convert to `Version 1.000; RELEASE` (and not `Version 1.000; RELEASE; DEV`) when the dev tag identified and vice versa.

TODO:

- [x] update docs with how this is approached as of v0.3.0
- [x] fix DEV/RELEASE duplication
- [x] fix `sha1`-dev/`sha1`-release duplication
- [x] fix `sha1` only dupes

**Comment by chrissimpkins** [comment]
Shouldn't be necessary because should be stamping new builds, but mistakes happen.  This supports change to the label added to the font.

**Comment by chrissimpkins** [comment]
Fix for `DEV`, `RELEASE`, `[sha1]-dev`,  and `[sha1]-release` added in https://github.com/source-foundry/font-v/commit/297f5b0eed38152e82e221e1579ae4ba83aeef44

**Comment by chrissimpkins** [comment]
Will be partial fix for now.  To fix the SHA1 issue, need to match on strings of hex characters.  This could perhaps unintentionally remove short words that were present in the version string before write?  For now, will update documentation to rebuild and try again.

**Comment by felipesanches** [comment]
Thanks! I clearly stumbled on this issue today when thinking about https://github.com/googlefonts/fontbakery/issues/1563 :-)

![screenshot at 2017-11-20 22 03 12](https://user-images.githubusercontent.com/213676/33047818-e1ad9d82-ce3e-11e7-9414-d79528413cab.png)

**Comment by chrissimpkins** [comment]
Any thoughts about how to approach https://github.com/source-foundry/font-v/issues/7#issuecomment-327504361?

I haven't come up with a good solution...

**Comment by chrissimpkins** [comment]
Can you show me the version of font-v that you are using in the SS above?  I thought that I fixed the DEV/RELEASE issue.  https://github.com/source-foundry/font-v/commit/297f5b0eed38152e82e221e1579ae4ba83aeef44. 

It should only affect the sha1 short strings at this point.

**Comment by chrissimpkins** [comment]
Was able to replicate this issue when there is no substring following the release/dev substring.  Looking into it.

**Comment by chrissimpkins** [comment]
Fixed and released as v0.3.2.  Available on PyPI.  Please let me know if this addressed the issue in https://github.com/source-foundry/font-v/issues/7#issuecomment-345872645 Felipe.  Thanks for noticing this. It only occurred when there were exactly two substrings delimited by `;` in the version string.

**Comment by chrissimpkins** [comment]
There will be a fix for the sha1 only dupes in the new libfv library and we will build this into the font-v executable after library release.

**Comment by chrissimpkins** [comment]
Potential for fix of the SHA1 only duplication issue in #22

**Comment by chrissimpkins** [comment]
libfv updated and this will be fixed as of v0.5.0 release.  Currently implemented in the `dev` branch.

**Comment by chrissimpkins** [comment]
fixed in v0.5.0 release
